services:
  app:
    build: .
    environment:
      PORT: 8000
      DRIVER: "posgres"
      ADDRESS: ${{secrets.DB_HOST}}
      DB_PORT: 5432
      USERNAME: ${{secrets.DB_USERNAME}}
      PASSWORD: ${{secrets.DB_PASSWORD}}
      NAME: ${{secrets.DB_NAME}}
    restart: always
    ports:
      - 8081:8000
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080