services:
  app:
    build: .
    environment:
      PORT: 8000
      DRIVER: "posgres"
      ADDRESS: ${DB_HOST}
      DB_PORT: 5432
      USERNAME: ${DB_USERNAME}
      PASSWORD: ${DB_PASSWORD}
      NAME: ${DB_NAME}
    restart: always
    ports:
      - 8081:8000
  adminer:
    image: adminer
    restart: always
    ports:
      - 9000:8080