apiVersion: apps/v1
kind: Deployment
metadata:
      name: go-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - image: mawan1122/backend-ewallet-hub:latest
        name: go-app
        env:
          - name: "PORT"
            value: "8000"
          - name: "DRIVER"
            value: "postgres"
          - name: "ADDRESS"
            value: ${{secrets.DB_HOST}}
          - name: "DB_PORT"
            value: "5432"
          - name: "USERNAME"
            value: ${{secrets.DB_USERNAME}}
          - name: "PASSWORD"
            value: ${{secrets.DB_PASSWORD}}
          - name: "NAME"
            value: ${{secrets.DB_NAME}}
          - name: "LOC"
            value: "Asia%2FJakarta"    
        ports:
           - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: go-app-service
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8000
  selector:
    app: go-app
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: go-app-ingress
  annotations:
    dev.okteto.com/generate-host: "domain"
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: go-app-service
          servicePort: 8080