name: Deploy
on: 
  push:
    branches:
      - "main"

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Setup QEMU
      uses: docker/setup-qemu-action@v1
      
    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login To DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and Push
      uses: docker/build-push-action@v2
      with: 
        push: true
        tags: mawan1122/backend-ewallet-hub:latest
    
    - name: checkout
      uses: actions/checkout@master
      
    - name: Login Okteto
      uses: okteto/login@master
      with:
        token: ${{ secrets.OKTETO_TOKEN }}
    
    - name: "Activate personal namespace"
      uses: okteto/namespace@master
      with:
        namespace: ademawan
        
    - name: "create deployment"
      uses: okteto/apply@master
      with:
        manifest: ./deployment/app-pod.yaml
    
    - uses: actions-hub/kubectl@master
      env:
       KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
      with:
       args: rollout restart deployment go-app-deployment
